import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type {
  ResourceAASProfile,
  ValidationIssue,
} from '../types/resourceaas';
import { SEMANTIC_ID_BASE } from '../aas/semanticIds';
import { api } from '../api/client';

/** Result of building+validating one AAS via POST /api/profile-to-aas. */
export interface BuildAasResult {
  aasJson: string;
  conforms: boolean;
  issues: ValidationIssue[];
}

export type AASType = 'Resource' | 'Product' | 'Process';
export type SubmodelKey =
  | 'Nameplate'
  | 'AID'
  | 'Skills'
  | 'Capabilities'
  | 'Variables'
  | 'Parameters'
  | 'HierarchicalStructures';

export type SubmodelTab = SubmodelKey;

export const REQUIRED_SUBMODELS: SubmodelKey[] = ['Nameplate', 'HierarchicalStructures'];

export const ALL_SUBMODELS: SubmodelKey[] = [
  'Nameplate',
  'HierarchicalStructures',
  'AID',
  'Skills',
  'Capabilities',
  'Variables',
  'Parameters',
];

export const SUBMODEL_FIELD_PREFIXES: Record<SubmodelKey, string[]> = {
  Nameplate: ['DigitalNameplate'],
  HierarchicalStructures: ['HierarchicalStructures'],
  AID: ['AID'],
  Skills: ['Skills'],
  Capabilities: ['Capabilities'],
  Variables: ['Variables'],
  Parameters: ['Parameters'],
};

export const SUBMODEL_YAML_KEYS: Record<SubmodelKey, string> = {
  Nameplate: 'DigitalNameplate',
  HierarchicalStructures: 'HierarchicalStructures',
  AID: 'AID',
  Skills: 'Skills',
  Capabilities: 'Capabilities',
  Variables: 'Variables',
  Parameters: 'Parameters',
};

// ── Per-AAS state ─────────────────────────────────────────────────────────────

export interface AASNodeState {
  identitySystemId: string;
  identityIdShort: string;
  identityId: string;
  identityGlobalAssetId: string;
  identityAssetType: string;
  aasType: AASType;
  selectedSubmodels: SubmodelKey[];
  parsedProfile: ResourceAASProfile | null;
}

export const DEFAULT_AAS_NODE_STATE: AASNodeState = {
  identitySystemId: '',
  identityIdShort: '',
  identityId: '',
  identityGlobalAssetId: '',
  identityAssetType: '',
  aasType: 'Resource',
  selectedSubmodels: [...REQUIRED_SUBMODELS],
  parsedProfile: null,
};

// ── AppState ──────────────────────────────────────────────────────────────────

interface AppState {
  // ── Multi-AAS ──────────────────────────────────────────────────────────
  aasNodes: Record<string, AASNodeState>;
  activeAasNodeId: string;

  // ── "Active AAS" workspace fields (flat copies of aasNodes[activeAasNodeId]) ──
  // These are kept in sync so all existing form code reads them unchanged.
  aasType: AASType;
  selectedSubmodels: SubmodelKey[];
  identitySystemId: string;
  identityIdShort: string;
  identityId: string;
  identityGlobalAssetId: string;
  identityAssetType: string;
  activeTab: SubmodelTab;
  parsedProfile: ResourceAASProfile | null;

  // ── Validation ──────────────────────────────────────────────────────────
  isLoadingValidate: boolean;                    // active AAS (mirrored from *ForNode)
  validationIssuesByNode: Record<string, ValidationIssue[]>;
  loadingValidateByNode: Record<string, boolean>;

  // ── Multi-AAS actions ───────────────────────────────────────────────────
  setActiveAasNode: (shellNodeId: string) => void;
  addAasNode: (shellNodeId: string) => void;
  removeAasNode: (shellNodeId: string) => void;
  resetAasNode: (shellNodeId: string) => void;
  buildAasJsonForNode: (shellNodeId: string, signal?: AbortSignal) => Promise<BuildAasResult | null>;
  buildAllAasJson: () => Promise<string>;

  // ── Existing actions (operate on active AAS) ────────────────────────────
  setAASType: (t: AASType) => void;
  setSelectedSubmodels: (s: SubmodelKey[]) => void;
  toggleSubmodel: (s: SubmodelKey) => void;
  setIdentityField: (field: 'systemId' | 'idShort' | 'id' | 'globalAssetId' | 'assetType', value: string) => void;
  initProfileFromIdentity: () => void;
  setActiveTab: (tab: SubmodelTab) => void;
  updateProfileField: (path: string[], value: unknown) => void;
  /** Directly update a specific AAS node's profile (bypasses active workspace swap). */
  updateProfileFieldForNode: (shellNodeId: string, path: string[], value: unknown) => void;
  /** Remove a nested key from a specific AAS node's profile. */
  removeProfileEntryForNode: (shellNodeId: string, path: string[]) => void;
  setValidationIssuesForNode: (nodeId: string, issues: ValidationIssue[]) => void;
  setLoadingValidateForNode: (nodeId: string, v: boolean) => void;
  resetAll: () => void;

  // ── AI Generation ───────────────────────────────────────────────────────
  /** Import an AAS JSON string generated by the AI pipeline into the active AAS node. */
  importAasJson: (json: string) => Promise<void>;

  // ── Theme ──────────────────────────────────────────────────────────────
  theme: 'light' | 'dark';
  toggleTheme: () => void;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function deriveBaseUrl(id: string): string {
  try {
    return new URL(id).origin;
  } catch {
    return SEMANTIC_ID_BASE;
  }
}

/** Flatten AASNodeState fields onto the "active workspace" fields. */
function flattenNode(ns: AASNodeState): Partial<AppState> {
  return {
    identitySystemId: ns.identitySystemId,
    identityIdShort: ns.identityIdShort,
    identityId: ns.identityId,
    identityGlobalAssetId: ns.identityGlobalAssetId,
    identityAssetType: ns.identityAssetType,
    aasType: ns.aasType,
    selectedSubmodels: ns.selectedSubmodels,
    parsedProfile: ns.parsedProfile,
  };
}

/** Extract the active workspace fields into an AASNodeState. */
function extractNodeState(s: AppState): AASNodeState {
  return {
    identitySystemId: s.identitySystemId,
    identityIdShort: s.identityIdShort,
    identityId: s.identityId,
    identityGlobalAssetId: s.identityGlobalAssetId,
    identityAssetType: s.identityAssetType,
    aasType: s.aasType,
    selectedSubmodels: s.selectedSubmodels,
    parsedProfile: s.parsedProfile,
  };
}

/** Apply workspace updates AND sync them back to aasNodes[activeAasNodeId]. */
function withSync(s: AppState, updates: Partial<AppState>): Partial<AppState> {
  return {
    ...updates,
    aasNodes: {
      ...s.aasNodes,
      [s.activeAasNodeId]: {
        identitySystemId: (updates.identitySystemId ?? s.identitySystemId),
        identityIdShort: (updates.identityIdShort ?? s.identityIdShort),
        identityId: (updates.identityId ?? s.identityId),
        identityGlobalAssetId: (updates.identityGlobalAssetId ?? s.identityGlobalAssetId),
        identityAssetType: (updates.identityAssetType ?? s.identityAssetType),
        aasType: (updates.aasType ?? s.aasType),
        selectedSubmodels: (updates.selectedSubmodels ?? s.selectedSubmodels),
        parsedProfile: (updates.parsedProfile ?? s.parsedProfile),
      },
    },
  };
}

/**
 * Reshape an AASNodeState into the profile-document wire body POST
 * /api/profile-to-aas expects — the exact shape
 * Transformation/AAS_Builder/AAS_builder.py::profile_document_to_aas_json
 * consumes. No AAS-element construction happens client-side any more; the
 * server (same builder code the LLM pipeline and validator use) does that.
 */
function buildProfilePayload(ns: AASNodeState): {
  asset_name: string;
  base_url: string;
  selected_submodels: string[];
  profile: Record<string, unknown>;
} {
  const systemId = ns.identitySystemId;
  const baseUrl = deriveBaseUrl(ns.identityId);
  const systemConfig = (ns.parsedProfile?.[systemId] ?? {}) as Record<string, unknown>;

  const merged: Record<string, unknown> = {
    ...systemConfig,
    idShort: ns.identityIdShort,
    id: ns.identityId,
    globalAssetId: ns.identityGlobalAssetId,
  };
  if (ns.identityAssetType) merged.assetType = ns.identityAssetType;

  return {
    asset_name: systemId,
    base_url: baseUrl,
    selected_submodels: ns.selectedSubmodels,
    profile: { [systemId]: merged },
  };
}

// ── Initial state ─────────────────────────────────────────────────────────────
// Canvas starts with zero AAS nodes -- every shell (including the first) is
// created explicitly via addAasNode, and can be deleted like any other.

const INITIAL_STATE = {
  aasNodes: {} as Record<string, AASNodeState>,
  activeAasNodeId: '',
  wizardStep: 0,
  aasType: 'Resource' as const,
  selectedSubmodels: [...REQUIRED_SUBMODELS] as SubmodelKey[],
  identitySystemId: '',
  identityIdShort: '',
  identityId: '',
  identityGlobalAssetId: '',
  identityAssetType: '',
  activeTab: 'Nameplate' as SubmodelKey,
  parsedProfile: null as ResourceAASProfile | null,
  isLoadingValidate: false,
  validationIssuesByNode: {} as Record<string, ValidationIssue[]>,
  loadingValidateByNode: {} as Record<string, boolean>,
  theme: 'light' as 'light' | 'dark',
};

// ── Store ─────────────────────────────────────────────────────────────────────

export const useAppStore = create<AppState>()(
  persist(
  (set, get) => ({
  ...INITIAL_STATE,

  // ── Multi-AAS actions ──────────────────────────────────────────────────

  setActiveAasNode: (shellNodeId) => {
    const s = get();
    // Save current workspace to the outgoing node
    const outgoing = extractNodeState(s);
    const incoming = s.aasNodes[shellNodeId] ?? DEFAULT_AAS_NODE_STATE;
    set({
      aasNodes: { ...s.aasNodes, [s.activeAasNodeId]: outgoing },
      activeAasNodeId: shellNodeId,
      ...flattenNode(incoming),
    });
  },

  addAasNode: (shellNodeId) => {
    const s = get();
    if (s.aasNodes[shellNodeId]) return; // already exists
    set({
      aasNodes: { ...s.aasNodes, [shellNodeId]: { ...DEFAULT_AAS_NODE_STATE } },
    });
  },

  removeAasNode: (shellNodeId) => {
    const s = get();
    const next = { ...s.aasNodes };
    delete next[shellNodeId];
    const updates: Partial<AppState> = { aasNodes: next };
    // If removed was active, switch to first remaining -- or to "no active AAS"
    // (empty string) if that was the last one. An empty canvas is a valid state.
    if (s.activeAasNodeId === shellNodeId) {
      const remaining = Object.keys(next);
      const fallback = remaining[0] ?? '';
      const fallbackState = next[fallback] ?? DEFAULT_AAS_NODE_STATE;
      Object.assign(updates, { activeAasNodeId: fallback, ...flattenNode(fallbackState) });
    }
    set(updates as AppState);
  },

  resetAasNode: (shellNodeId) => {
    const s = get();
    const fresh = { ...DEFAULT_AAS_NODE_STATE };
    const next = { ...s.aasNodes, [shellNodeId]: fresh };
    const updates: Partial<AppState> = { aasNodes: next };
    if (s.activeAasNodeId === shellNodeId) {
      Object.assign(updates, flattenNode(fresh));
    }
    set(updates as AppState);
  },

  buildAasJsonForNode: async (shellNodeId, signal?: AbortSignal) => {
    const s = get();
    // Use the live workspace if it's the active node, otherwise use saved state
    const ns = s.activeAasNodeId === shellNodeId
      ? extractNodeState(s)
      : (s.aasNodes[shellNodeId] ?? DEFAULT_AAS_NODE_STATE);
    if (!ns.identitySystemId) return null;
    const res = await api.profileToAas(buildProfilePayload(ns), signal);
    return { aasJson: res.aas_json, conforms: res.conforms, issues: res.issues };
  },

  buildAllAasJson: async () => {
    const s = get();
    // Collect current workspace state for active node, saved state for others
    const allNodes = {
      ...s.aasNodes,
      [s.activeAasNodeId]: extractNodeState(s),
    };
    const configured = Object.values(allNodes).filter((ns) => ns.identitySystemId);
    const results = await Promise.all(
      configured.map((ns) => api.profileToAas(buildProfilePayload(ns)))
    );
    const envs = results.map((r) => JSON.parse(r.aas_json));
    return JSON.stringify(envs, null, 2);
  },

  // ── Wizard actions ─────────────────────────────────────────────────────

  setAASType: (t) => set((s) => withSync(s, { aasType: t }) as AppState),

  setSelectedSubmodels: (subs) => set((s) => withSync(s, { selectedSubmodels: subs }) as AppState),

  toggleSubmodel: (sm) => {
    const s = get();
    if (REQUIRED_SUBMODELS.includes(sm)) return;
    const isAdding = !s.selectedSubmodels.includes(sm);
    const next = isAdding
      ? [...s.selectedSubmodels, sm]
      : s.selectedSubmodels.filter((x) => x !== sm);

    let parsedProfile = s.parsedProfile;
    if (parsedProfile && s.identitySystemId) {
      const clone = JSON.parse(JSON.stringify(parsedProfile)) as Record<string, unknown>;
      const sysCfg = (clone[s.identitySystemId] ?? {}) as Record<string, unknown>;
      const profileKey = SUBMODEL_YAML_KEYS[sm];
      if (isAdding) {
        if (!(profileKey in sysCfg)) sysCfg[profileKey] = {};
      } else {
        const val = sysCfg[profileKey];
        if (val === null || val === undefined || (typeof val === 'object' && Object.keys(val as object).length === 0)) {
          delete sysCfg[profileKey];
        }
      }
      clone[s.identitySystemId] = sysCfg;
      parsedProfile = clone as ResourceAASProfile;
    }
    set(withSync(s, { selectedSubmodels: next, parsedProfile }) as AppState);
  },

  setIdentityField: (field, value) => {
    const map = {
      systemId: 'identitySystemId', idShort: 'identityIdShort',
      id: 'identityId', globalAssetId: 'identityGlobalAssetId', assetType: 'identityAssetType',
    } as const;
    set((s) => withSync(s, { [map[field]]: value }) as AppState);
  },

  initProfileFromIdentity: () => {
    const s = get();
    const { identitySystemId, identityIdShort, identityId, identityGlobalAssetId, selectedSubmodels, parsedProfile } = s;
    if (!identitySystemId) return;

    if (parsedProfile && parsedProfile[identitySystemId]) {
      const existing = parsedProfile[identitySystemId];
      const updated = { ...existing };
      let changed = false;
      for (const sm of selectedSubmodels) {
        const key = SUBMODEL_YAML_KEYS[sm] as keyof typeof updated;
        if (!(key in updated)) {
          (updated as Record<string, unknown>)[key] = {};
          changed = true;
        }
      }
      if (changed) set(withSync(s, { parsedProfile: { ...parsedProfile, [identitySystemId]: updated } }) as AppState);
      return;
    }

    const submodelEntries = Object.fromEntries(selectedSubmodels.map((sm) => [SUBMODEL_YAML_KEYS[sm], {}]));
    const profile: ResourceAASProfile = {
      [identitySystemId]: { idShort: identityIdShort, id: identityId, globalAssetId: identityGlobalAssetId, ...submodelEntries },
    };
    set(withSync(s, { parsedProfile: profile }) as AppState);
  },

  // ── Form actions ───────────────────────────────────────────────────────

  setActiveTab: (tab) => set({ activeTab: tab }),

  updateProfileField: (path, value) => {
    const s = get();
    if (!s.parsedProfile) return;
    const clone = JSON.parse(JSON.stringify(s.parsedProfile)) as Record<string, unknown>;
    let node: Record<string, unknown> = clone;
    for (let i = 0; i < path.length - 1; i++) {
      if (!node[path[i]] || typeof node[path[i]] !== 'object') node[path[i]] = {};
      node = node[path[i]] as Record<string, unknown>;
    }
    node[path[path.length - 1]] = value;
    set(withSync(s, { parsedProfile: clone as ResourceAASProfile }) as AppState);
  },

  updateProfileFieldForNode: (shellNodeId, path, value) => {
    const s = get();
    const ns = s.aasNodes[shellNodeId];
    if (!ns?.parsedProfile) return;
    const clone = JSON.parse(JSON.stringify(ns.parsedProfile)) as Record<string, unknown>;
    let node: Record<string, unknown> = clone;
    for (let i = 0; i < path.length - 1; i++) {
      if (!node[path[i]] || typeof node[path[i]] !== 'object') node[path[i]] = {};
      node = node[path[i]] as Record<string, unknown>;
    }
    node[path[path.length - 1]] = value;
    const updatedNs = { ...ns, parsedProfile: clone as ResourceAASProfile };
    set({
      aasNodes: { ...s.aasNodes, [shellNodeId]: updatedNs },
      ...(s.activeAasNodeId === shellNodeId ? { parsedProfile: clone as ResourceAASProfile } : {}),
    });
  },

  removeProfileEntryForNode: (shellNodeId, path) => {
    const s = get();
    const ns = s.aasNodes[shellNodeId];
    if (!ns?.parsedProfile) return;
    const clone = JSON.parse(JSON.stringify(ns.parsedProfile)) as Record<string, unknown>;
    let node: Record<string, unknown> = clone;
    for (let i = 0; i < path.length - 1; i++) {
      if (!node[path[i]] || typeof node[path[i]] !== 'object') return;
      node = node[path[i]] as Record<string, unknown>;
    }
    delete node[path[path.length - 1]];
    const updatedNs = { ...ns, parsedProfile: clone as ResourceAASProfile };
    set({
      aasNodes: { ...s.aasNodes, [shellNodeId]: updatedNs },
      ...(s.activeAasNodeId === shellNodeId ? { parsedProfile: clone as ResourceAASProfile } : {}),
    });
  },

  // ── Validation actions ─────────────────────────────────────────────────

  setValidationIssuesForNode: (nodeId, issues) =>
    set((s) => ({
      validationIssuesByNode: { ...s.validationIssuesByNode, [nodeId]: issues },
    })),

  setLoadingValidateForNode: (nodeId, v) =>
    set((s) => ({
      loadingValidateByNode: { ...s.loadingValidateByNode, [nodeId]: v },
      ...(nodeId === s.activeAasNodeId ? { isLoadingValidate: v } : {}),
    })),

  // ── AI Generation import ───────────────────────────────────────────────

  importAasJson: async (json: string) => {
    let parsed: Awaited<ReturnType<typeof api.aasToProfile>>;
    try {
      parsed = await api.aasToProfile(json);
    } catch (exc) {
      console.error('importAasJson: failed to parse AAS JSON', exc);
      return;
    }

    const { selected_submodels, profile } = parsed;
    const systemId = Object.keys(profile)[0];
    if (!systemId) {
      console.error('importAasJson: no system found in parsed profile');
      return;
    }
    const systemConfig = profile[systemId] as Record<string, unknown>;

    // selected_submodels already comes back as SubmodelKey-shaped strings
    // (see _SUBMODEL_IDSHORT_TO_KEY in aas_to_profile.py) — no idShort
    // translation needed on this side.
    const finalKeys = [...new Set([...REQUIRED_SUBMODELS, ...(selected_submodels as SubmodelKey[])])];

    const updates: Partial<AppState> = {
      identitySystemId: systemId,
      identityIdShort: (systemConfig.idShort as string) ?? '',
      identityId: (systemConfig.id as string) ?? '',
      identityGlobalAssetId: (systemConfig.globalAssetId as string) ?? '',
      selectedSubmodels: finalKeys,
      parsedProfile: { [systemId]: systemConfig } as unknown as ResourceAASProfile,
    };

    set((s) => withSync(s, updates) as AppState);
  },

  // ── Theme ──────────────────────────────────────────────────────────────

  toggleTheme: () => {
    const next = get().theme === 'light' ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', next);
    set({ theme: next });
  },

  // ── Reset ──────────────────────────────────────────────────────────────

  resetAll: () => set({ ...INITIAL_STATE }),
  }),
  {
    name: 'resourceaas-app',
    partialize: (s) => ({
      aasNodes: s.aasNodes,
      activeAasNodeId: s.activeAasNodeId,
      aasType: s.aasType,
      selectedSubmodels: s.selectedSubmodels,
      identitySystemId: s.identitySystemId,
      identityIdShort: s.identityIdShort,
      identityId: s.identityId,
      identityGlobalAssetId: s.identityGlobalAssetId,
      identityAssetType: s.identityAssetType,
      parsedProfile: s.parsedProfile,
      theme: s.theme,
    }),
  }
));
